/**
 * Hardcoded mock data for offline / no-backend deployments.
 * Shape mirrors the Supabase `public` schema rows used by the UI.
 */

const now = new Date().toISOString();

const cover = (seed: string, w = 600, h = 900) =>
  `https://picsum.photos/seed/${encodeURIComponent(seed)}/${w}/${h}`;

export const mockSeries = [
  {
    id: "s1", slug: "aurora-knight", title: "Aurora Knight",
    type: "manga", status: "ongoing",
    author: "Kim Mira", artist: "Kim Mira",
    description: "A young knight bonded to a star-spirit must defend the kingdom of Lior from creeping shadow.",
    cover_url: cover("aurora-knight"), banner_url: cover("aurora-knight-bnr", 1600, 700),
    genres: ["Action", "Fantasy", "Adventure", "Magic"],
    is_trending: true, is_popular: true,
    views: 128400, rating: 4.8,
    created_at: now, updated_at: now,
  },
  {
    id: "s2", slug: "moonlit-academy", title: "Moonlit Academy",
    type: "manga", status: "ongoing",
    author: "Hana Sato", artist: "Hana Sato",
    description: "At an academy hidden in the clouds, a transfer student discovers her family's forbidden magic.",
    cover_url: cover("moonlit-academy"), banner_url: cover("moonlit-academy-bnr", 1600, 700),
    genres: ["Romance", "Fantasy", "School Life", "Magic"],
    is_trending: true, is_popular: true,
    views: 98230, rating: 4.6,
    created_at: now, updated_at: now,
  },
  {
    id: "s3", slug: "echoes-of-mu", title: "Echoes of Mu",
    type: "manga", status: "completed",
    author: "Ren Aoki", artist: "Ren Aoki",
    description: "A drifter walks the ruins of a sunken continent, listening for songs only he can hear.",
    cover_url: cover("echoes-of-mu"), banner_url: cover("echoes-of-mu-bnr", 1600, 700),
    genres: ["Mystery", "Supernatural", "Adventure", "Drama"],
    is_trending: true, is_popular: true,
    views: 76210, rating: 4.7,
    created_at: now, updated_at: now,
  },
  {
    id: "s4", slug: "crimson-vow", title: "Crimson Vow",
    type: "manga", status: "ongoing",
    author: "Yuna Park", artist: "Yuna Park",
    description: "Bound by an oath of blood, two rival heirs must rule a city built on secrets.",
    cover_url: cover("crimson-vow"),
    genres: ["Drama", "Romance", "Action"],
    is_trending: false, is_popular: true,
    views: 54120, rating: 4.5,
    created_at: now, updated_at: now,
  },
  {
    id: "s5", slug: "stardust-runner", title: "Stardust Runner",
    type: "manga", status: "ongoing",
    author: "Lia Chen",
    description: "A courier surfs solar winds to deliver impossible packages across the system.",
    cover_url: cover("stardust-runner"),
    genres: ["Adventure", "Action", "Supernatural"],
    is_trending: false, is_popular: true,
    views: 41210, rating: 4.4,
    created_at: now, updated_at: now,
  },
  {
    id: "s6", slug: "garden-of-veils", title: "Garden of Veils",
    type: "novel", status: "ongoing",
    author: "M. Holloway",
    description: "Inside a walled garden, a gardener tends flowers that whisper the names of the dead.",
    cover_url: cover("garden-of-veils"),
    genres: ["Mystery", "Drama", "Supernatural"],
    is_trending: false, is_popular: false,
    views: 18230, rating: 4.6,
    created_at: now, updated_at: now,
  },
  {
    id: "s7", slug: "salt-and-storm", title: "Salt and Storm",
    type: "novel", status: "ongoing",
    author: "Adia Vale",
    description: "A lighthouse keeper's daughter bargains with the sea to save her drowning village.",
    cover_url: cover("salt-and-storm"),
    genres: ["Fantasy", "Adventure", "Drama"],
    is_trending: false, is_popular: false,
    views: 15330, rating: 4.5,
    created_at: now, updated_at: now,
  },
  {
    id: "s8", slug: "paper-lanterns", title: "Paper Lanterns",
    type: "novel", status: "completed",
    author: "Toshi Aren",
    description: "Every winter solstice the lanterns rise, and one of them carries a wish that comes true.",
    cover_url: cover("paper-lanterns"),
    genres: ["Romance", "Drama", "Supernatural"],
    is_trending: false, is_popular: false,
    views: 12110, rating: 4.7,
    created_at: now, updated_at: now,
  },
  {
    id: "s9", slug: "ironwood-court", title: "Ironwood Court",
    type: "manga", status: "hiatus",
    author: "Sera Liu",
    description: "In a forest of living iron, an exiled princess forges allies from her enemies.",
    cover_url: cover("ironwood-court"),
    genres: ["Fantasy", "Action", "Drama"],
    is_trending: false, is_popular: true,
    views: 33020, rating: 4.3,
    created_at: now, updated_at: now,
  },
  {
    id: "s10", slug: "comet-club", title: "Comet Club",
    type: "manga", status: "ongoing",
    author: "Ito Mei",
    description: "Five misfits start an after-school club to track a comet that only they can see.",
    cover_url: cover("comet-club"),
    genres: ["Comedy", "School Life", "Supernatural"],
    is_trending: false, is_popular: true,
    views: 27810, rating: 4.5,
    created_at: now, updated_at: now,
  },
  {
    id: "s11", slug: "verdant-hex", title: "Verdant Hex",
    type: "manga", status: "ongoing",
    author: "N. Okafor",
    description: "A botanist learns that the city's parks are an enormous spell waiting to be triggered.",
    cover_url: cover("verdant-hex"),
    genres: ["Mystery", "Magic", "Supernatural"],
    is_trending: false, is_popular: true,
    views: 22610, rating: 4.4,
    created_at: now, updated_at: now,
  },
  {
    id: "s12", slug: "neon-saints", title: "Neon Saints",
    type: "manga", status: "ongoing",
    author: "Vex Kuro",
    description: "On the rooftops of a glowing megacity, a band of vigilantes negotiates with old gods.",
    cover_url: cover("neon-saints"),
    genres: ["Action", "Supernatural", "Drama"],
    is_trending: false, is_popular: true,
    views: 39120, rating: 4.6,
    created_at: now, updated_at: now,
  },
];

export const mockChapters = mockSeries.flatMap((s) =>
  Array.from({ length: 4 }).map((_, i) => ({
    id: `${s.id}-c${i + 1}`,
    series_id: s.id,
    number: 4 - i,
    title: `Chapter ${4 - i}`,
    content: null,
    is_premium: i === 0,
    coin_cost: i === 0 ? 5 : 0,
    created_at: now,
    updated_at: now,
  })),
);

export const mockSiteSettings = {
  id: true,
  site_name: "Nuvia Toon",
  seo_description: "Discover trending manhwa and novels with a magical reading experience.",
};
