// This file is automatically generated. Do not edit it directly.
// NOTE: Patched to gracefully fall back to a MOCK client when Supabase env
// vars are missing (or when VITE_USE_MOCK=true). This lets the site render
// statically on a VPS without any backend configured.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockSeries, mockChapters, mockSiteSettings } from '@/lib/mock-data';

function envFlag(v: unknown): boolean {
  return typeof v === 'string' && (v === '1' || v.toLowerCase() === 'true');
}

function shouldUseMock(): boolean {
  const forced = envFlag(import.meta.env.VITE_USE_MOCK);
  if (forced) return true;
  const url = import.meta.env.VITE_SUPABASE_URL || (typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined);
  const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);
  return !url || !key;
}

/* ------------------------------ MOCK CLIENT ------------------------------ */

type Row = Record<string, unknown>;

function tableData(table: string): Row[] {
  switch (table) {
    case 'series': return mockSeries as unknown as Row[];
    case 'chapters': return mockChapters as unknown as Row[];
    case 'site_settings': return [mockSiteSettings] as unknown as Row[];
    default: return [];
  }
}

interface Filter { kind: 'eq' | 'in' | 'ilike' | 'contains'; col: string; val: unknown }
interface Order { col: string; ascending: boolean }

function applyFilters(rows: Row[], filters: Filter[]): Row[] {
  return rows.filter((r) => filters.every((f) => {
    const v = r[f.col];
    switch (f.kind) {
      case 'eq': return v === f.val;
      case 'in': return Array.isArray(f.val) && (f.val as unknown[]).includes(v);
      case 'ilike': {
        if (typeof v !== 'string' || typeof f.val !== 'string') return false;
        const pat = f.val.replace(/%/g, '').toLowerCase();
        return v.toLowerCase().includes(pat);
      }
      case 'contains':
        if (Array.isArray(v) && Array.isArray(f.val)) return (f.val as unknown[]).every((x) => (v as unknown[]).includes(x));
        return false;
    }
  }));
}

function makeQueryBuilder(table: string) {
  const filters: Filter[] = [];
  let orderBy: Order | null = null;
  let limit: number | null = null;
  let rangeFrom: number | null = null;
  let rangeTo: number | null = null;

  const exec = () => {
    let rows = applyFilters(tableData(table), filters);
    if (orderBy) {
      const { col, ascending } = orderBy;
      rows = [...rows].sort((a, b) => {
        const av = a[col]; const bv = b[col];
        if (av === bv) return 0;
        if (av == null) return 1; if (bv == null) return -1;
        return (av < bv ? -1 : 1) * (ascending ? 1 : -1);
      });
    }
    const total = rows.length;
    if (rangeFrom != null && rangeTo != null) rows = rows.slice(rangeFrom, rangeTo + 1);
    else if (limit != null) rows = rows.slice(0, limit);
    return { data: rows, count: total };
  };

  const builder: Record<string, unknown> = {
    select: (_cols?: string, _opts?: { count?: string }) => builder,
    eq: (col: string, val: unknown) => { filters.push({ kind: 'eq', col, val }); return builder; },
    in: (col: string, val: unknown[]) => { filters.push({ kind: 'in', col, val }); return builder; },
    ilike: (col: string, val: string) => { filters.push({ kind: 'ilike', col, val }); return builder; },
    contains: (col: string, val: unknown) => { filters.push({ kind: 'contains', col, val }); return builder; },
    order: (col: string, opts?: { ascending?: boolean }) => { orderBy = { col, ascending: opts?.ascending !== false }; return builder; },
    limit: (n: number) => { limit = n; return builder; },
    range: (from: number, to: number) => { rangeFrom = from; rangeTo = to; return builder; },
    maybeSingle: () => Promise.resolve({ data: exec().data[0] ?? null, error: null, count: null }),
    single: () => Promise.resolve({ data: exec().data[0] ?? null, error: null, count: null }),
    then: (onF: (v: { data: Row[]; error: null; count: number }) => unknown, onR?: (e: unknown) => unknown) => {
      try {
        const { data, count } = exec();
        return Promise.resolve({ data, error: null, count }).then(onF, onR);
      } catch (e) { return Promise.resolve().then(() => onR?.(e)); }
    },
    insert: () => Promise.resolve({ data: null, error: null }),
    update: () => Promise.resolve({ data: null, error: null }),
    delete: () => Promise.resolve({ data: null, error: null }),
    upsert: () => Promise.resolve({ data: null, error: null }),
  };
  return builder;
}

function createMockClient(): unknown {
  const noopChannel = {
    on: () => noopChannel,
    subscribe: () => noopChannel,
    unsubscribe: () => Promise.resolve('ok' as const),
  };
  return {
    from: (table: string) => makeQueryBuilder(table),
    auth: {
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      onAuthStateChange: (_cb: unknown) => ({ data: { subscription: { unsubscribe: () => undefined } } }),
      signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: { message: 'Backend not configured (mock mode).' } }),
      signUp: () => Promise.resolve({ data: { user: null, session: null }, error: { message: 'Backend not configured (mock mode).' } }),
      signOut: () => Promise.resolve({ error: null }),
    },
    channel: () => noopChannel,
    removeChannel: () => Promise.resolve('ok' as const),
    storage: { from: () => ({ upload: () => Promise.resolve({ data: null, error: null }), getPublicUrl: () => ({ data: { publicUrl: '' } }) }) },
    functions: { invoke: () => Promise.resolve({ data: null, error: null }) },
  };
}

/* ------------------------------ REAL CLIENT ------------------------------ */

function createRealSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);
  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _client: unknown;
function getClient(): unknown {
  if (_client) return _client;
  if (shouldUseMock()) {
    if (typeof console !== 'undefined') console.warn('[Supabase] Using MOCK client (no backend configured).');
    _client = createMockClient();
  } else {
    _client = createRealSupabaseClient();
  }
  return _client;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createRealSupabaseClient>, {
  get(_, prop, receiver) {
    return Reflect.get(getClient() as object, prop, receiver);
  },
});
