// This file is automatically generated. Do not edit it directly.
// NOTE: Patched to route data calls to:
//   1. Laravel API (when VITE_API_URL is set) — production mode
//   2. Mock data (when no API + no Supabase) — VPS preview mode
//   3. Real Supabase (legacy fallback) — only if Supabase env vars exist and no Laravel
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockSeries, mockChapters, mockSiteSettings } from '@/lib/mock-data';
import { HAS_LARAVEL_API, api, setAuthToken, clearAuthToken, getAuthToken, ApiError } from '@/lib/api';
import { makeLaravelQueryBuilder, laravelRpc } from '@/lib/laravel-data';

function envFlag(v: unknown): boolean {
  return typeof v === 'string' && (v === '1' || v.toLowerCase() === 'true');
}

type Mode = 'laravel' | 'mock' | 'supabase';
function detectMode(): Mode {
  if (HAS_LARAVEL_API) return 'laravel';
  if (envFlag(import.meta.env.VITE_USE_MOCK)) return 'mock';
  const url = import.meta.env.VITE_SUPABASE_URL || (typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined);
  const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);
  if (url && key) return 'supabase';
  return 'mock';
}

/* ------------------------------ MOCK CLIENT ------------------------------ */
type Row = Record<string, unknown>;

function tableData(table: string): Row[] {
  switch (table) {
    case 'series': return mockSeries as unknown as Row[];
    case 'chapters': return mockChapters as unknown as Row[];
    case 'site_settings': return [mockSiteSettings] as unknown as Row[];
    default: return [];
  }
}

interface Filter { kind: 'eq' | 'in' | 'ilike' | 'contains' | 'neq'; col: string; val: unknown }
interface Order { col: string; ascending: boolean }

function applyFilters(rows: Row[], filters: Filter[]): Row[] {
  return rows.filter((r) => filters.every((f) => {
    const v = r[f.col];
    switch (f.kind) {
      case 'eq': return v === f.val;
      case 'neq': return v !== f.val;
      case 'in': return Array.isArray(f.val) && (f.val as unknown[]).includes(v);
      case 'ilike': {
        if (typeof v !== 'string' || typeof f.val !== 'string') return false;
        return v.toLowerCase().includes(f.val.replace(/%/g, '').toLowerCase());
      }
      case 'contains':
        if (Array.isArray(v) && Array.isArray(f.val)) return (f.val as unknown[]).every((x) => (v as unknown[]).includes(x));
        return false;
    }
  }));
}

function makeMockQueryBuilder(table: string) {
  const filters: Filter[] = [];
  let orderBy: Order | null = null;
  let limit: number | null = null;
  let rangeFrom: number | null = null;
  let rangeTo: number | null = null;

  const exec = () => {
    let rows = applyFilters(tableData(table), filters);
    if (orderBy) {
      const { col, ascending } = orderBy;
      rows = [...rows].sort((a, b) => {
        const av = a[col]; const bv = b[col];
        if (av === bv) return 0;
        if (av == null) return 1; if (bv == null) return -1;
        return (av < bv ? -1 : 1) * (ascending ? 1 : -1);
      });
    }
    const total = rows.length;
    if (rangeFrom != null && rangeTo != null) rows = rows.slice(rangeFrom, rangeTo + 1);
    else if (limit != null) rows = rows.slice(0, limit);
    return { data: rows, count: total };
  };

  const b: Record<string, unknown> = {
    select: () => b,
    eq: (col: string, val: unknown) => { filters.push({ kind: 'eq', col, val }); return b; },
    neq: (col: string, val: unknown) => { filters.push({ kind: 'neq', col, val }); return b; },
    in: (col: string, val: unknown[]) => { filters.push({ kind: 'in', col, val }); return b; },
    ilike: (col: string, val: string) => { filters.push({ kind: 'ilike', col, val }); return b; },
    contains: (col: string, val: unknown) => { filters.push({ kind: 'contains', col, val }); return b; },
    order: (col: string, opts?: { ascending?: boolean }) => { orderBy = { col, ascending: opts?.ascending !== false }; return b; },
    limit: (n: number) => { limit = n; return b; },
    range: (from: number, to: number) => { rangeFrom = from; rangeTo = to; return b; },
    maybeSingle: () => Promise.resolve({ data: exec().data[0] ?? null, error: null, count: null }),
    single: () => Promise.resolve({ data: exec().data[0] ?? null, error: null, count: null }),
    then: (onF: (v: { data: Row[]; error: null; count: number }) => unknown, onR?: (e: unknown) => unknown) => {
      try {
        const { data, count } = exec();
        return Promise.resolve({ data, error: null, count }).then(onF, onR);
      } catch (e) { return Promise.resolve().then(() => onR?.(e)); }
    },
    insert: () => Promise.resolve({ data: null, error: null }),
    update: () => Promise.resolve({ data: null, error: null }),
    delete: () => Promise.resolve({ data: null, error: null }),
    upsert: () => Promise.resolve({ data: null, error: null }),
  };
  return b;
}

/* ------------------------------ LARAVEL AUTH ------------------------------ */
type AuthListener = (event: string, session: unknown) => void;
const authListeners = new Set<AuthListener>();
let cachedUser: { id: string; email?: string; user_metadata?: Record<string, unknown> } | null = null;

function emitAuth(event: string) {
  const session = cachedUser ? { user: cachedUser, access_token: getAuthToken() } : null;
  authListeners.forEach((cb) => { try { cb(event, session); } catch { /* ignore */ } });
}

async function loadUserFromApi() {
  try {
    const u = await api.get<{ id: number | string; email?: string; name?: string }>('/user', { silent: true });
    cachedUser = {
      id: String(u.id),
      email: u.email,
      user_metadata: { display_name: u.name },
    };
  } catch {
    cachedUser = null;
    if (getAuthToken()) clearAuthToken();
  }
}

function createLaravelClient(): unknown {
  // Hydrate on boot if we have a token
  if (typeof window !== 'undefined' && getAuthToken() && !cachedUser) {
    loadUserFromApi().then(() => emitAuth('INITIAL_SESSION'));
  }

  const noopChannel = {
    on: () => noopChannel,
    subscribe: () => noopChannel,
    unsubscribe: () => Promise.resolve('ok' as const),
  };

  return {
    from: (table: string) => makeLaravelQueryBuilder(table),
    rpc: (name: string, params: Record<string, unknown>) => laravelRpc(name, params),
    auth: {
      getSession: async () => {
        if (!cachedUser && getAuthToken()) await loadUserFromApi();
        const session = cachedUser ? { user: cachedUser, access_token: getAuthToken() } : null;
        return { data: { session }, error: null };
      },
      getUser: async () => {
        if (!cachedUser && getAuthToken()) await loadUserFromApi();
        return { data: { user: cachedUser }, error: null };
      },
      onAuthStateChange: (cb: AuthListener) => {
        authListeners.add(cb);
        return { data: { subscription: { unsubscribe: () => { authListeners.delete(cb); } } } };
      },
      signInWithPassword: async ({ email, password }: { email: string; password: string }) => {
        try {
          const r = await api.post<{ token: string; user: { id: number | string; email?: string; name?: string } }>(
            '/login', { email, password }, { anonymous: true },
          );
          setAuthToken(r.token);
          cachedUser = { id: String(r.user.id), email: r.user.email, user_metadata: { display_name: r.user.name } };
          emitAuth('SIGNED_IN');
          return { data: { user: cachedUser, session: { user: cachedUser, access_token: r.token } }, error: null };
        } catch (e) {
          return { data: { user: null, session: null }, error: { message: e instanceof ApiError ? e.message : 'Sign in failed' } };
        }
      },
      signUp: async ({ email, password, options }: { email: string; password: string; options?: { data?: { display_name?: string } } }) => {
        try {
          const name = options?.data?.display_name ?? email.split('@')[0];
          const r = await api.post<{ token: string; user: { id: number | string; email?: string; name?: string } }>(
            '/register', { name, email, password, password_confirmation: password }, { anonymous: true },
          );
          setAuthToken(r.token);
          cachedUser = { id: String(r.user.id), email: r.user.email, user_metadata: { display_name: r.user.name } };
          emitAuth('SIGNED_IN');
          return { data: { user: cachedUser, session: { user: cachedUser, access_token: r.token } }, error: null };
        } catch (e) {
          return { data: { user: null, session: null }, error: { message: e instanceof ApiError ? e.message : 'Sign up failed' } };
        }
      },
      signOut: async () => {
        try { await api.post('/logout'); } catch { /* ignore */ }
        clearAuthToken();
        cachedUser = null;
        emitAuth('SIGNED_OUT');
        return { error: null };
      },
    },
    channel: () => noopChannel,
    removeChannel: () => Promise.resolve('ok' as const),
    storage: { from: () => ({ upload: () => Promise.resolve({ data: null, error: null }), getPublicUrl: () => ({ data: { publicUrl: '' } }) }) },
    functions: { invoke: () => Promise.resolve({ data: null, error: null }) },
  };
}

/* ------------------------------ MOCK CLIENT ------------------------------ */
function createMockClient(): unknown {
  const noopChannel = {
    on: () => noopChannel,
    subscribe: () => noopChannel,
    unsubscribe: () => Promise.resolve('ok' as const),
  };
  return {
    from: (table: string) => makeMockQueryBuilder(table),
    rpc: () => Promise.resolve({ data: { success: false, error: 'Backend not configured (mock mode).' }, error: null }),
    auth: {
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
      signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: { message: 'Backend not configured (mock mode).' } }),
      signUp: () => Promise.resolve({ data: { user: null, session: null }, error: { message: 'Backend not configured (mock mode).' } }),
      signOut: () => Promise.resolve({ error: null }),
    },
    channel: () => noopChannel,
    removeChannel: () => Promise.resolve('ok' as const),
    storage: { from: () => ({ upload: () => Promise.resolve({ data: null, error: null }), getPublicUrl: () => ({ data: { publicUrl: '' } }) }) },
    functions: { invoke: () => Promise.resolve({ data: null, error: null }) },
  };
}

/* ------------------------------ REAL SUPABASE ------------------------------ */
function createRealSupabaseClient() {
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || (typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || (typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined);
  return createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _client: unknown;
function getClient(): unknown {
  if (_client) return _client;
  const mode = detectMode();
  if (typeof console !== 'undefined') {
    console.info(`[DataClient] Mode: ${mode.toUpperCase()}`);
  }
  if (mode === 'laravel') _client = createLaravelClient();
  else if (mode === 'supabase') _client = createRealSupabaseClient();
  else _client = createMockClient();
  return _client;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createRealSupabaseClient>, {
  get(_, prop, receiver) {
    return Reflect.get(getClient() as object, prop, receiver);
  },
});
