// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
  (import.meta.env.VITE_SUPABASE_URL as string | undefined) ||
  (typeof process !== 'undefined' ? (process.env?.SUPABASE_URL as string | undefined) : undefined) ||
  'https://rjwdxbnsnrahvogcyxld.supabase.co';

const SUPABASE_PUBLISHABLE_KEY =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ||
  (typeof process !== 'undefined' ? (process.env?.SUPABASE_PUBLISHABLE_KEY as string | undefined) : undefined) ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqd2R4Ym5zbnJhaHZvZ2N5eGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc0ODQyODgsImV4cCI6MjA5MzA2MDI4OH0.3RV7YSUo0_kf0K-UPsqYL1zRzq2aa7ZuEQ0UnjgVQq4';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  },
});
